"use strict";

var _interopRequireDefault = require("@babel/runtime/helpers/interopRequireDefault");

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.getAllPermissionsFor = exports.getPermissionsMap = exports.validatePermissions = exports.parsePermissions = exports.loadPermissions = exports.hasAllPermissions = exports.hasAnyPermission = exports.getFullGroupPermission = void 0;

var _defineProperty2 = _interopRequireDefault(require("@babel/runtime/helpers/defineProperty"));

var _requireAll = _interopRequireDefault(require("require-all"));

function ownKeys(object, enumerableOnly) { var keys = Object.keys(object); if (Object.getOwnPropertySymbols) { var symbols = Object.getOwnPropertySymbols(object); if (enumerableOnly) symbols = symbols.filter(function (sym) { return Object.getOwnPropertyDescriptor(object, sym).enumerable; }); keys.push.apply(keys, symbols); } return keys; }

function _objectSpread(target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i] != null ? arguments[i] : {}; if (i % 2) { ownKeys(source, true).forEach(function (key) { (0, _defineProperty2["default"])(target, key, source[key]); }); } else if (Object.getOwnPropertyDescriptors) { Object.defineProperties(target, Object.getOwnPropertyDescriptors(source)); } else { ownKeys(source).forEach(function (key) { Object.defineProperty(target, key, Object.getOwnPropertyDescriptor(source, key)); }); } } return target; }

/**
 * Generate the full group permission string for the passed permission i.e if
 * the permission is [user.create] it returns [user.*] which is the full
 * permission for the user permission group. If the permission is
 * already a full group permission it returns it.
 *
 * @param permission
 * @returns {*}
 */
var getFullGroupPermission = function getFullGroupPermission(permission) {
  if (permission.indexOf('*') >= 0) {
    return permission;
  }

  return "".concat(permission.substr(0, permission.lastIndexOf('.')), ".*");
};
/**
 * Check whether the user has any valid permission. If the list of valid permissions
 * is empty it returns true since it is basically checking against nothing.
 *
 * @param userPermissions
 * @param validPermissions
 * @returns boolean
 */


exports.getFullGroupPermission = getFullGroupPermission;

var hasAnyPermission = function hasAnyPermission(userPermissions, validPermissions) {
  if (!validPermissions.length) {
    return true;
  }

  var hasAnyValid = false;
  validPermissions.forEach(function (permission) {
    if (userPermissions.indexOf(permission) >= 0 || userPermissions.indexOf(getFullGroupPermission(permission)) >= 0) {
      hasAnyValid = true;
    }
  });
  return hasAnyValid;
};
/**
 * Check whether the user has all the required permissions. If the list of required permissions
 * is empty it returns true since it is basically checking against nothing.
 *
 * @param userPermissions
 * @param requiredPermissions
 * @returns boolean
 */


exports.hasAnyPermission = hasAnyPermission;

var hasAllPermissions = function hasAllPermissions(userPermissions, requiredPermissions) {
  var hasAllRequired = true;
  requiredPermissions.forEach(function (permission) {
    if (userPermissions.indexOf(permission) < 0 && userPermissions.indexOf(getFullGroupPermission(permission)) < 0) {
      hasAllRequired = false;
    }
  });
  return hasAllRequired;
};
/**
 * Loads the permissions defined on the specified path. When loading, the permission
 * objects are added to an object. The actions are each prefixed with the name of
 * the entity. It also adds an object with all the permissions.
 *
 * @param pathName
 * @returns {{$all: {}}}
 */


exports.hasAllPermissions = hasAllPermissions;

var loadPermissions = function loadPermissions(pathName) {
  var permissions = {
    $all: {}
  };
  var permissionsObj = (0, _requireAll["default"])(pathName);
  Object.keys(permissionsObj).forEach(function (permission) {
    var actions = {};
    var actionsObj = permissionsObj[permission]["default"] ? permissionsObj[permission]["default"] : permissionsObj[permission];
    Object.keys(actionsObj).forEach(function (action) {
      actions["".concat(permission, ".").concat(action)] = actionsObj[action];
    });
    permissions.$all = _objectSpread({}, permissions.$all, {}, actions);
    permissions[permission] = actions;
  });
  return permissions;
};
/**
 * Parses the permissions defined on the specified object into an object similar to
 * the one generated by loadPermissions(). When loading, the permission objects
 * are added to an object. The actions are each prefixed with the name of the
 * entity. It also adds an object with all the permissions.
 *
 * @returns {{$all: {}}}
 * @param permissionsObj
 */


exports.loadPermissions = loadPermissions;

var parsePermissions = function parsePermissions(permissionsObj) {
  var permissions = {
    $all: {}
  };
  Object.keys(permissionsObj).forEach(function (permission) {
    var actions = {};
    var actionsObj = permissionsObj[permission];
    Object.keys(actionsObj).forEach(function (action) {
      actions["".concat(permission, ".").concat(action)] = actionsObj[action];
    });
    permissions.$all = _objectSpread({}, permissions.$all, {}, actions);
    permissions[permission] = actions;
  });
  return permissions;
};
/**
 * Checks a list of permissions against the system permissions. It returns an
 * object with two values: valid (boolean) indicating whether its valid and
 * invalids (list) with any invalid permission that may be found.
 *
 * @param systemPermissions
 * @param permissions
 * @returns {{invalids: Array, isValid: boolean}}
 */


exports.parsePermissions = parsePermissions;

var validatePermissions = function validatePermissions(systemPermissions, permissions) {
  var isValid = true;
  var invalids = [];
  var systemPermissionKeys = Object.keys(systemPermissions);
  permissions.forEach(function (permission) {
    if (systemPermissionKeys.indexOf(permission) < 0) {
      isValid = false;
      invalids.push(permission);
    }
  });
  return {
    isValid: isValid,
    invalids: invalids
  };
};
/**
 * Get an object containing mappings (key : description) of permissions. The mapping
 * is based on the defined system permissions.
 *
 * @param systemPermissions
 * @param permissions
 * @returns {*}
 */


exports.validatePermissions = validatePermissions;

var getPermissionsMap = function getPermissionsMap(systemPermissions, permissions) {
  var permissionsMap = {};
  permissions.forEach(function (permission) {
    permissionsMap[permission] = systemPermissions[permission];
  });
  return permissionsMap;
};
/**
 * Get all the permissions for an entity. For example passing 'x' will
 * return [ 'x.*', 'x.view', 'c.create', ..., ].
 *
 * @param systemPermissions
 * @param entity
 * @returns {string[]}
 */


exports.getPermissionsMap = getPermissionsMap;

var getAllPermissionsFor = function getAllPermissionsFor(systemPermissions, entity) {
  return Object.keys(systemPermissions).filter(function (permission) {
    return permission.startsWith(entity);
  });
};

exports.getAllPermissionsFor = getAllPermissionsFor;